"""ai_core/constants.py: Standardized node names for LangGraph."""

# Node Names
CONTEXT_LOADER_NODE = "context_loader_node"
HUMAN_INPUT_NODE = "human_input_node"
ROUTER_NODE = "router_node"
VISION_NODE = "vision_node"
EXTRACT_CROP_AGE_NODE = "extract_crop_age_node"
FOLLOW_UP_GENERATION_NODE = "follow_up_generation_node" 
REQUEST_IMAGE_NODE = "request_image_node"
GENERAL_CHAT_NODE = "general_chat_node"
SYMPTOM_ALIGNMENT_NODE = "symptom_alignment_node"
RAG_SEARCH_NODE = "rag_search_node"
UNIVERSAL_FALLBACK_NODE = "universal_fallback_node"
RERANKER_NODE = "reranker_node"
FETCH_TREATMENT_NODE="fetch_treatment_node"
INVESTIGATIVE_QUESTION_NODE="investigative_question_node"
SYMPTOM_REFINEMENT_NODE="symptom_refinement_node"
CONTEXT_ENRICHMENT_NODE="context_enrichment_node"
DIAGNOSIS_GENERATOR_NODE="diagnosis_generator_node"
SAFETY_CRITIC_NODE="safety_critic_node"