"""Graph state definitions for the Paddy Disease Diagnostic engine."""

from typing import Any, TypedDict

from schemas.ai_models import CropStage


class PaddyGraphState(TypedDict, total=False):
    # 1. Session & Memory
    user_id: str
    """Unique identifier for the farmer (used to load active crop cycle and GPS)."""

    cycle_id: str
    """Primary session ID linking to the active crop season."""

    user_text: str
    """Current farmer query text."""

    images: list[str]
    """List of crop image base64 strings."""

    new_uploaded_images: list[str]
    """Temporary buffer for images uploaded during a human-in-the-loop pause."""

    recent_chat_history: str | None
    """Short-term memory (last 6 messages)."""

    medical_timeline: str | None
    """The historical log of all past diagnoses and treatments for this cycle."""

    # 2. Agronomic Context
    location: dict[str, float]
    """Farm GPS coordinates for the weather tool {'lat': float, 'lon': float}."""

    planting_date: str | None
    """Sowing/transplanting date in ISO 8601 format (YYYY-MM-DD)."""

    crop_age_days: int | None
    """Calculated elapsed days since planting."""

    crop_stage: CropStage | None
    """Identified growth stage."""

    # 3. Vision Processing
    is_image_rejected: bool
    """True if the image is out-of-domain (e.g., person, floor), unreadable, or fails internal confidence thresholds."""

    visual_text: str | None
    """Pathological features extracted from images."""

    # 4. Clarification & Synthesis
    have_question: bool
    """True if ambiguity requires asking the farmer a clarification question."""

    clarifying_question: str | None
    """The exact question generated to resolve ambiguity."""

    clarification_answer: str | None
    """The farmer's direct reply to the clarifying_question."""

    clarification_history: list[dict[str, str]]
    """
    Isolated histories per node. 
    """

    aligned_symptom_profile: str | None
    """Fused summary of visual symptoms and user text."""

    router_destination: str | None
    """The designated next node path determined by the router (e.g., 'vision_node', 'general_chat_node')."""

    # 5. Vector Retrieval
    retrieved_candidate_chunks: list[dict[str, Any]]
    """Raw disease vectors retrieved from pgvector."""

    top_candidate_disease_id: str | None
    """UUID of the highest-ranked disease match."""

    top_candidate_score: float | None
    """Similarity score of the top candidate."""

    # 6. Relational Truth Data
    disease_name: str | None
    """Standardized disease name fetched from PostgreSQL."""

    treatment_guide_doc: str | None
    """Strict, factual treatment steps fetched from PostgreSQL."""

    weather_constraints: dict[str, Any] | None
    """JSON constraints for safe chemical application."""

    # 7. Tools
    weather_context: str | None
    """The 11-day Markdown report generated by the Open-Meteo tool."""

    # 8. Critic & Safety
    is_approved: bool | None
    """True if the draft is 100% grounded, weather-safe, and formatted correctly."""

    critic_feedback: str | None
    """Internal correction instructions if safety checks fail."""

    retry_count: int
    """Tracks loops to prevent infinite graph execution."""

    paused_by: str | None
    """Records the exact node constant that triggered the pause."""

    # 9. Output
    final_diagnosis: str | None
    """The finalized, localized advisory message for the farmer."""
